<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Techno-311" failures="1" tests="1" name="AddIdentity" time="4.848" errors="0" timestamp="27 May 2024 07:53:44 GMT">
  <testcase classname="io.mosip.testrig.apirig.testscripts.AddIdentity" name="" time="4.654">
    <failure type="io.mosip.testrig.apirig.admin.fw.util.AdminTestException" message="Failed at output validation">
      <![CDATA[io.mosip.testrig.apirig.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testrig.apirig.testscripts.AddIdentity.test(AddIdentity.java:158)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:197)
	at io.mosip.testrig.apirig.testrunner.MosipTestRunner.main(MosipTestRunner.java:140)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!--  -->
</testsuite> <!-- AddIdentity -->
