<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Techno-311" failures="3" tests="6" name="AuthLock" time="17.324" errors="0" timestamp="16 Nov 2022 08:49:21 GMT">
  <testcase classname="io.mosip.testscripts.PostWithBodyWithOtpGenerate" name="" time="5.615"/>
  <testcase classname="io.mosip.testscripts.PostWithBodyWithOtpGenerate" name="Mimoto_AuthLock_Valid_UIN_All" time="4.481"/>
  <testcase classname="io.mosip.testscripts.PostWithBodyWithOtpGenerate" name="Mimoto_AuthLock_InValid_Otp_All" time="2.402"/>
  <testcase classname="io.mosip.testscripts.PostWithBodyWithOtpGenerate" name="Mimoto_AuthLock_with_invalidUIN_Valid_Otp_sid" time="0.834">
    <failure type="io.mosip.admin.fw.util.AdminTestException" message="Failed at otp output validation">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at otp output validation
	at io.mosip.testscripts.PostWithBodyWithOtpGenerate.test(PostWithBodyWithOtpGenerate.java:94)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:164)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Mimoto_AuthLock_with_invalidUIN_Valid_Otp_sid -->
  <testcase classname="io.mosip.testscripts.PostWithBodyWithOtpGenerate" name="Mimoto_AuthLock_Valid_VID_All" time="1.925">
    <failure type="io.mosip.admin.fw.util.AdminTestException" message="Failed at output validation">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.PostWithBodyWithOtpGenerate.test(PostWithBodyWithOtpGenerate.java:117)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:164)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Mimoto_AuthLock_Valid_VID_All -->
  <testcase classname="io.mosip.testscripts.PostWithBodyWithOtpGenerate" name="Mimoto_AuthLock_with_invalidVID_Valid_Otp" time="2.051">
    <failure type="io.mosip.admin.fw.util.AdminTestException" message="Failed at output validation">
      <![CDATA[io.mosip.admin.fw.util.AdminTestException: Failed at output validation
	at io.mosip.testscripts.PostWithBodyWithOtpGenerate.test(PostWithBodyWithOtpGenerate.java:117)
	at io.mosip.testrunner.MosipTestRunner.startTestRunner(MosipTestRunner.java:164)
	at io.mosip.testrunner.MosipTestRunner.main(MosipTestRunner.java:111)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Mimoto_AuthLock_with_invalidVID_Valid_Otp -->
</testsuite> <!-- AuthLock -->
